require([
    'src/view/base',
    'src/view/common',
    'src/view/sunday',
    'src/view/sunnight',
    'src/view/overcastday',
    'src/view/rainday',
    'src/view/dustday',
    'src/view/cloudyday',
    'src/view/bgScene',
    'src/view/warnScene'
]);